# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d9cddebb54c337c509b32349f7102adcf64eac82df70612ce015ce64b375c09681d84f36fdc31a06b04d446a2d80d8bca644648ead08c12649b22be03f73b6e

test:
  secret_key_base: f1684853b6c709e49e280075595336694d09e2e03654fdc8cca2fc4f5d8551a627d7f4b75e628381a44feab3054c02242ff1d132064fdf8a4827c66840a5446d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
